lynx-family/lynx-website

rspress.config.ts

https://github.com/web-infra-dev/rspress/blob/51fe6572da38914f1bdea4f5de48f23818182d2d/packages/document/rspress.config.ts#L81

feat(theme): add EditLink and some translation

---

docs/en/api/elements/built-in/view.mdx
docs/zh/api/elements/built-in/view.mdx

add className attribute  description for ReactLynx
Change-Id: Ie7dfbd33e32099cb4698eb6887a02c734bb10a44

feat: add className des

---

docs/en/rspeedy/_meta.json
docs/en/rspeedy/upgrade.md
docs/zh/rspeedy/_meta.json
docs/zh/rspeedy/upgrade.md

> [!WARNING]
> ~~Merge this until https://github.com/lynx-family/lynx-stack/pull/145 is merged and published~~
>
> Merged and published!

docs(rspeedy): add upgrade-rspeedy

---

docs/en/guide/start/quick-start.mdx
docs/zh/guide/start/quick-start.mdx
src/components/go/example-preview/components/index.tsx
src/components/platform-tabs/PlatformTabs.tsx

Change-Id: I7094695e70f0fc80b659bac41fbeae70531e63e6

feat: update link

---

rspress.config.ts

Change-Id: Ie4b5d5acc9d6f56d839953b68a3034157fd8ac22
fix: og-image-url

fix: og-image-url

---

docs/en/guide/start/fragments/web/integrating-lynx-with-web.mdx
docs/en/guide/start/quick-start.mdx
docs/en/react/introduction.mdx

Change-Id: Ib50bfc801fed5e7b9ed10d45fdba06bfec53cf9d
- Entry the created project → **Navigate to the created project**
- Checkout the builtin elements that Lynx have → **Check out the built-in elements that Lynx provides**
- Learn how to thinking in the ReactLynx framework → **Learn how to think in the ReactLynx framework**

Fixed Grammar issues

---

docs/en/api/elements/built-in/image.mdx
docs/zh/api/elements/built-in/image.mdx

Change-Id: Iea340a74c7074316930238506bc892f1c4f1877d

docs: update supported image formats and SVG rendering guidance

---

README.md

Change-Id: I733b81dbebdc7d1caec1c3b44b2b51990459b50f

opt: readme-credits

---

docs/en/react/thinking-in-reactlynx.mdx
docs/zh/react/thinking-in-reactlynx.mdx

See: https://github.com/lynx-family/lynx-stack/pull/153

docs(react): `useImperativeHandle` should be background only

---

docs/en/react/main-thread-script.mdx
docs/zh/react/main-thread-script.mdx

See: https://github.com/lynx-family/lynx-stack/pull/119
Change-Id: I3f8828c5d214873638bd92deebe1a4b1c051b969

feat: improve examples in mts docs

---

docs/en/api/css/properties/perspective.mdx
docs/en/api/css/properties/text-stroke.mdx
docs/zh/api/css/properties/perspective.mdx

Change-Id: I911c8b0fff4c23dbfd637d176067c1fb71101419

feat: refine pespective api des

---

docs/en/guide/ui/layout/index.mdx

https://lynxjs.org/guide/ui/layout/

Reduced over-linking for better readability

---

docs/en/api/css/properties/transition-delay.mdx
docs/en/api/elements/built-in/image.mdx
docs/zh/api/css/properties/border-left-color.mdx

- Remove duplicate PropertyDefinition import in transition-delay.mdx
- Standardize anchor point format in image.mdx
- Remove unused Go component import in border-left-color.mdx
Change-Id: I8d3dd22ac189c5d667f8e7f9090992f6ad0dc36e

chore(docs): clean up documentation files

---

docs/en/guide/start/quick-start.mdx

yea, the grammar is pretty bad, will try and fix more later

fix spelling and grammar in quick-start.mdx

---

docs/en/guide/use-data-from-host-platform.mdx
docs/zh/guide/use-data-from-host-platform.mdx

Change-Id: Icca8b06199be9070faffc1f92f839f19b9728463
fix: #18

docs: correct android meta data update example

---

docs/zh/guide/start/tutorial-gallery.mdx

docs: Remove redundant blank

---

docs/en/rspeedy/styling.mdx
docs/zh/rspeedy/styling.mdx

Change-Id: Ia1623b2e59a9f868af0342b2a832852ce4671d31

feat: add tailwindcss to styling.mdx

---

docs/en/rspeedy/styling.mdx
docs/zh/rspeedy/styling.mdx

Reverts lynx-family/lynx-website#63

Revert "feat: add tailwindcss to styling.mdx"

---

theme/index.scss

Reverts lynx-family/lynx-website#26

Revert "[BugFix] [ui] Hero Text is overflowing out of screen for some phone and tablet devices"

---

package.json
pnpm-lock.yaml
rspress.config.ts

Change-Id: I8da4532ac5a618ccc56d5a56eac461643f907937

feat: support google-analytics

---

docs/en/guide/start/fragments/web/integrating-lynx-with-web.mdx

Change-Id: I2bb93b04174996112fc30e484157ad8462fde337

chore: lynx web should use main.web.bundle

---

docs/en/guide/start/fragments/web/integrating-lynx-with-web.mdx
docs/zh/guide/start/fragments/web/integrating-lynx-with-web.mdx

fix https://github.com/lynx-family/lynx-website/issues/78
Change-Id: I24f16db1ff2d91f2c4abfef206f33fb3e99cb939

docs(integrate web): add import

---

packages/lynx-compat-data/lynx-api/lynx/performance.json

Change-Id: I5c6c9fd760c9a963b9b240667e5fc9b9ee3a18d5

fix: lynx.performance.createObserver is unavailable in web

---

cspell.json
docs/en/blog/index.mdx
docs/en/blog/lynx-open-source-roadmap-2025.mdx
docs/zh/blog/index.mdx
docs/zh/blog/lynx-open-source-roadmap-2025.mdx
src/components/blog-avatar/authors.json

Change-Id: Icc9f2c8af859592ed95da0250c18322ab587ee37

Update Lynx 2025 Roadmap

---

docs/en/api/css/at-rule/font-face.mdx
docs/en/api/elements/built-in/text.mdx
docs/en/guide/styling/text-and-typography.mdx
docs/zh/api/css/at-rule/font-face.mdx
docs/zh/api/elements/built-in/text.mdx
docs/zh/guide/styling/text-and-typography.mdx
packages/lynx-compat-data/css/at-rule/font-face.json
packages/lynx-example-packages/package.json
pnpm-lock.yaml

Change-Id: I38c1b46b8aed2b7ec052b1fa79ce7df73cfad399

feat:optimize text and css at-rule doc.

---

docs/en/guide/debugging/lynx-devtool/elements-panel.mdx
docs/en/guide/debugging/lynx-devtool/layers-panel.mdx
docs/zh/guide/debugging/lynx-devtool/elements-panel.mdx
docs/zh/guide/debugging/lynx-devtool/layers-panel.mdx

Change-Id: I56e58d04874a23c9e132d034590036e26ba110c2

Adjust the image layout in the element panel and layer panel

---

src/components/EditThis/index.tsx
src/components/RuleItem.tsx
src/components/code-fold/index.tsx
src/components/go/example-preview/components/code-view.tsx
src/components/go/example-preview/components/index.tsx
src/components/go/example-preview/components/web-iframe.tsx
src/components/home-comps/banner/DotPattern.tsx
src/components/home-comps/border-beam/index.tsx

Change-Id: Iddf94f614788472f72630ea2f0c03793f0993d59
- fix components tailwind prefix，eg: w-full -> sh-w-full

fix(components): fix tailwind prefix

---

docs/en/guide/debugging/lynx-devtool/elements-panel.mdx
docs/en/guide/debugging/lynx-devtool/layers-panel.mdx
docs/zh/guide/debugging/lynx-devtool/elements-panel.mdx
docs/zh/guide/debugging/lynx-devtool/layers-panel.mdx

Change-Id: Ie3d2a4c27a2f6c74eb51c2daed4a53958843eca4

Adjust the image margin in the element panel and layer panel

---

docs/en/guide/start/tutorial-gallery.mdx
docs/zh/guide/start/tutorial-gallery.mdx

This pull provides sample images used in the tutorial
Fixed: https://github.com/lynx-family/lynx-website/issues/112
Change-Id: Ibe08201ad562387d21216e5a5a65580f50fc92c4

feat: Add assets package in tutorial

---

.npmignore
package.json
pnpm-lock.yaml
scripts/lynx-example.js
src/components/go/Go.tsx
src/components/go/example-preview/components/code-view.tsx
src/components/go/example-preview/components/code.tsx
src/components/go/example-preview/components/index.module.scss
src/components/go/example-preview/components/index.tsx
src/components/go/example-preview/components/preview-img.tsx
src/components/go/example-preview/components/resizable.tsx
src/components/go/example-preview/components/switch-schema.tsx
src/components/go/example-preview/components/web-iframe.tsx
src/components/go/example-preview/hooks/use-switch-schema.ts
src/components/go/example-preview/index.tsx
src/components/go/example-preview/utils/example-data.ts
src/components/go/example-preview/utils/icon.tsx
src/components/go/example-preview/utils/tool.ts
src/components/platform-tabs/PlatformTabs.tsx
theme/AfterNavTitle.tsx
theme/BeforeSidebar.tsx
theme/hero-text.scss
theme/home-layout-var.scss
theme/index.scss
theme/index.tsx
theme/subsite-ui.tsx

- Go support right footer params
- support npm package

feat: support npm package

---

docs/en/api/elements/built-in/list.mdx
packages/lynx-compat-data/elements/list.json

Change-Id: Ie09d93fedec370265f572916448374c69ff8f8f4
also need to update the version of @lynx-example/list

feat: add list web preview

---

docs/en/api/elements/built-in/text.mdx
docs/zh/api/elements/built-in/text.mdx
packages/lynx-example-packages/package.json
pnpm-lock.yaml

Change-Id: Ibb8c712acd8a37ae70fd6645320938afa0e81285

feat:add text selection API.

---

docs/en/api/elements/built-in/list.mdx
docs/zh/api/elements/built-in/list.mdx
packages/lynx-compat-data/lynx-api/lynx/queueMicrotask.json

Change-Id: I34ebd6290cb133301a18353a928a97f78c8f7c0a

 docs: update some version and multi platform error

---

docs/en/api/elements/built-in/text.mdx
docs/zh/api/elements/built-in/text.mdx
packages/lynx-example-packages/package.json
pnpm-lock.yaml

Change-Id: I463a79ee257f97607557d1e00bb38d9b32105219

 docs: update text selection docs

---

docs/en/api/elements/built-in/list.mdx
docs/en/api/elements/built-in/scroll-view.mdx
docs/zh/api/elements/built-in/list.mdx
docs/zh/api/elements/built-in/scroll-view.mdx
packages/lynx-compat-data/elements/list-item.json
packages/lynx-compat-data/elements/list.json

Change-Id: I015d51f5c9651feb77e1dfc04d8932fdde91ba07

opt: update <list> <list-item> <scroll-view> compat data

---

docs/en/api/elements/built-in/text.mdx
docs/zh/api/elements/built-in/text.mdx
packages/lynx-compat-data/elements/text.json

Change-Id: Iee92b2458466bd1ad3075951d78ad4ff1337034d

opti:update <text> compt data.

---

packages/lynx-compat-data/elements/list-item.json
packages/lynx-compat-data/elements/list.json
packages/lynx-compat-data/elements/scroll-view.json

Change-Id: If608f0116da3b0080fc65cf9bead9f5a5841ed4e

opt: add category in list and scroll-view's compat data

---

docs/en/api/elements/built-in/list.mdx
docs/zh/api/elements/built-in/list.mdx
packages/lynx-compat-data/elements/list-item.json
packages/lynx-compat-data/elements/list.json

Change-Id: Ifa9abd64df3ff8470a19c691802890116acf8aba

opt: modify list's compat data

---

docs/en/api/elements/built-in/list.mdx
docs/en/api/elements/built-in/text.mdx
docs/zh/api/elements/built-in/list.mdx
docs/zh/api/elements/built-in/text.mdx

Change-Id: I6920330585b133ee27e4760b5719aa2e46801853

  opt: fix tyo and add nested text compat data.

---

api-reports/rspeedy.json

fix: update link path

---

docs/en/guide/custom-native-component/custom-component-android.mdx
docs/en/guide/custom-native-modules/native-module-android.mdx
docs/en/guide/custom-native-modules/native-module-ios.mdx
docs/zh/guide/custom-native-component/custom-component-android.mdx
docs/zh/guide/custom-native-modules/native-module-android.mdx
docs/zh/guide/custom-native-modules/native-module-ios.mdx

Change-Id: I999b7eca36047afe569192a444e66124ab63240b
close https://github.com/lynx-family/lynx-website/issues/95
close https://github.com/lynx-family/lynx-website/issues/155
close https://github.com/lynx-family/lynx-website/pull/159
https://github.com/lynx-family/lynx-website/pull/152

fix: white screen of custom native component

---

api-reports/rspeedy.json

Should include `performance.profile`

docs: update api-reports

---

docs/en/api/elements/built-in/text.mdx
docs/zh/api/elements/built-in/text.mdx
packages/lynx-compat-data/elements/inline-truncation.json
packages/lynx-compat-data/elements/nested-image.json
packages/lynx-compat-data/elements/nested-text.json
packages/lynx-compat-data/elements/text.json

Change-Id: I6df5eeba02c9a45c72fc2db86d71788ad4cc9a62

doc:optimize text doc.

---

docs/en/blog/lynx-3-2.mdx
docs/zh/blog/lynx-3-2.mdx

Change-Id: Ib3c6e7327d9aacd992b4c4d67e18a6f71491d63a

fix(typo): Update lynx-3-2.mdx

---

docs/en/api/lynx-api/lynx/lynx-global-props.mdx
docs/zh/api/lynx-api/lynx/lynx-global-props.mdx

Hello, I'd like to provide an example of how to extend the `GlobalProps` interface to make TS "happy" and save other users the trouble.

Add an example of extending the `GlobalProps` interface

---

packages/lynx-compat-data/css/properties/linear-direction.json

Change-Id: I767a8abd089281e1e5dc38b8819ac6d7f283a14b

fix: web do not support deprecated value of linear-direction

---

docs/en/api/lynx-api/lynx/lynx-global-props.mdx

Some spelling errors slipped unnoticed last time. Here is an improved version.

Improve spelling and wording

---

docs/en/guide/styling/custom-theming.mdx
docs/en/guide/ui/styling.mdx
docs/zh/guide/styling/custom-theming.mdx
docs/zh/guide/ui/styling.mdx

close: #178
Change-Id: Ibbfe7c35dfec5fb803d72b9e61ed3e9082e71ff2

feat: opt styling doc

---

src/components/go/example-preview/components/code.tsx
src/components/go/example-preview/components/index.tsx

Change-Id: Ia7678298c460b769ec05aa251db47affe00c0439
introduced in #189

fix(component): scroll sometimes fails in <ExamplePreview />

---

docs/en/react/_meta.json
docs/en/rspeedy/_meta.json
docs/zh/react/_meta.json
docs/zh/rspeedy/_meta.json

docs: broken nav labels

---

docs/en/guide/start/fragments/ios/integrating-lynx-with-existing-app-ios.mdx
docs/zh/guide/start/fragments/ios/integrating-lynx-with-existing-app-ios.mdx

Change-Id: I3a5e1237fb126397ce16ad0514bb4fd20afcd247

fix: optimize ui of iOS integration doc.

---

docs/en/rspeedy/typescript.md
docs/zh/rspeedy/typescript.md

issue: https://github.com/lynx-family/lynx-website/issues/183.
You may also see an example in https://github.com/lynx-family/lynx-examples/pull/78.
> [!NOTE]
> I didn't use `<Go />` since there is not TypeScript intellisense there :)

docs: extending `NativeModules`

---

docs/en/api/lynx-native-api/template-data.mdx
docs/zh/api/lynx-native-api/template-data.mdx

Change-Id: Ib493261a352bd69a0c5c0fac1b5f8ff16fe9f26a

fix: fixing wrong doc title of template-data section

---

docs/en/react/lifecycle.mdx
docs/zh/react/lifecycle.mdx

https://github.com/lynx-family/lynx-stack/pull/770
Change-Id: I1fbd72d59f29411ff6dbe0965346abedb1c05df1

feat(react): docs for new changes of ref & effect lifecycle

---

theme/BeforeSidebar.tsx
theme/hooks/use-blog-btn-dom.ts
theme/index.tsx

Change-Id: I361490a43307b89de958e3db4b33ee60d92e99be

fix: support deploy to domain with subpath

---

theme/subsite-ui.tsx

Change-Id: If73ab7d3196694a9814441e263d8d5bbe267c5ae

fix: use server base for relative link

---

docs/en/api/css/properties/relative-center.mdx
docs/en/api/css/properties/relative-id.mdx
docs/zh/api/css/properties/relative-id.mdx

Change-Id: Ice4400d25aec2834c907625508df5ed01f21f0f7

Fix/css formal syntax in docs (relative-id, relative-center)

---

docs/en/guide/use-data-from-host-platform.mdx
docs/zh/guide/use-data-from-host-platform.mdx

Add "Using Data from Host Platform" doc on HarmonyOS
Change-Id: I9f3f2075e84e8b914eac10b7d09fa9aaa0ebd3ad

feat(docs): Add user data guide on HarmonyOS

---

docs/zh/api/elements/built-in/list.mdx
docs/zh/api/elements/built-in/scroll-view.mdx
docs/zh/api/elements/built-in/view.mdx
docs/zh/api/lynx-native-api/resource-fetcher/MediaResourceFetcher.mdx
packages/lynx-compat-data/elements/common.json
packages/lynx-compat-data/elements/image.json
packages/lynx-compat-data/elements/inline-truncation.json
packages/lynx-compat-data/elements/list-item.json
packages/lynx-compat-data/elements/list.json
packages/lynx-compat-data/elements/nested-image.json
packages/lynx-compat-data/elements/nested-text.json
packages/lynx-compat-data/elements/scroll-view.json
packages/lynx-compat-data/elements/text.json
packages/lynx-compat-data/elements/view.json

Add Lynx element API for harmony

fix(docs): Add Lynx element API for harmony

---

docs/en/guide/custom-native-component.mdx
docs/en/guide/custom-native-component/custom-component-harmony.mdx

Add custom element for HarmonyOS in English

fix(docs): Add custom element for HarmonyOS in English

---

docs/en/api/elements/built-in/list.mdx
docs/en/api/elements/built-in/scroll-view.mdx
docs/en/api/elements/built-in/view.mdx

Add element API for HarmonyOS in English

feat(docs):Add element API for HarmonyOS in English

---

packages/lynx-compat-data/elements/view.json

Add `name` property to `view` for HarmonyOS

feat(docs): Add `name` property to `view` for HarmonyOS

---

docs/en/guide/custom-native-modules/native-module-android.mdx
docs/en/guide/custom-native-modules/native-module-harmony.mdx
docs/en/guide/custom-native-modules/native-module-ios.mdx
docs/en/guide/use-native-modules.mdx
docs/zh/guide/custom-native-modules/native-module-android.mdx
docs/zh/guide/custom-native-modules/native-module-harmony.mdx
docs/zh/guide/custom-native-modules/native-module-ios.mdx
docs/zh/guide/use-native-modules.mdx

Change-Id: I27d83a2080e3d19455550a75243cd7b54abf2877

[feat] Add custom native module guide for harmony

---

pnpm-lock.yaml

Change-Id: Idf6d052741ca76f3107ddd0db31deb3e8d414653

 infra: update some dependcy

---

src/components/platform-tabs/PlatformTabs.tsx

Change-Id: I40cdc55f0da3f711e6af995b1ef92aafaf342cdb

chore: move `harmony` tab location

---

docs/en/api/lynx-native-api/lynx-load-meta.mdx
docs/zh/api/lynx-native-api/lynx-load-meta.mdx

feat(docs): update LynxLoadMeta API docs
Change-Id: Id7775eebf3c9b8662c0282fb4afb344cf5ad18db

feat(docs): update LynxLoadMeta API docs

---

packages/lynx-compat-data/elements/image.json

The HarmonyOS Image component has been updated to fully support animation scenarios.

docs: Update image compat data

---

docs/en/guide/custom-native-component/custom-component-harmony.mdx
docs/zh/guide/custom-native-component/custom-component-harmony.mdx

docs: Add a link to the HarmonyOS custom component doc

docs: Add a link to the HarmonyOS custom component doc

---

src/components/api-table/FetchingCompatTable.tsx
src/components/go/example-preview/index.tsx
src/lib/utils.ts

Change-Id: I32c029ae67fa8e8849bcb1bc024b6dbee1ab2a21

feat: exmaple base url support site base

---

docs/en/react/routing/tanstack-router.mdx
docs/zh/react/routing/tanstack-router.mdx

Change-Id: Ie2ef72e3f23ebcc1485cbf02d88e23562e1b58a5

docs: polish tanstack router

---

docs/en/react/index.mdx
docs/en/rspeedy/index.md
docs/zh/react/index.mdx
docs/zh/rspeedy/index.md

Change-Id: I575ae753468cd7d4b8a35985bc98bdf730ed9807

fix: hero button urls 404

---

docs/en/react/lifecycle.mdx
docs/zh/react/lifecycle.mdx

Change-Id: I9b63abed5edd2d6585007a3c10c51ceac8151d50

docs: update lifecycle diagram from v2 to v3

---

src/components/home-comps/banner/index.tsx

Change-Id: Ib693b706cafd9983ec0a35b56bdf26ecf8498213

fix: home bottom text missing

---

docs/en/guide/start/integrate-lynx-devtool-advanced.mdx
docs/en/guide/start/integrate-lynx-devtool.mdx
docs/zh/guide/start/integrate-lynx-devtool-advanced.mdx
docs/zh/guide/start/integrate-lynx-devtool.mdx

Change-Id: Idb0a84f86008b071f0dbb9147c4c057d539eec39

feat(docs): add integrate-lynx-devtool-advanced for harmony

---

docs/en/guide/debugging/lynx-devtool/_meta.json
docs/en/guide/debugging/lynx-devtool/preact-devtools-panel.mdx
docs/zh/guide/debugging/lynx-devtool/_meta.json
docs/zh/guide/debugging/lynx-devtool/preact-devtools-panel.mdx

Change-Id: I56f74d1594da85d85ae0d77df48a6fd0b88ff33a
Related PR: 
- https://github.com/lynx-family/lynx-devtool/pull/56
- https://github.com/lynx-family/lynx-stack/pull/1173

feat: add preact devtools docs

---

theme/AfterNavTitle.tsx

Change-Id: I2676fee73d3b80a9d7cb8e70c441805c1500a544

fix: a to link

---

docs/en/api/_meta.json
docs/zh/api/_meta.json

Change-Id: Ia3762fe57c7afe1ed6b89de43cf1c38ce5a9a490

fix: fix build error

---

docs/en/api/elements/built-in/_meta.json
docs/en/api/elements/built-in/frame.mdx
docs/zh/api/elements/built-in/_meta.json
docs/zh/api/elements/built-in/frame.mdx
packages/lynx-compat-data/elements/frame.json

feat: add Lynx frame docs
Change-Id: Ib0a599e00e214652c6ae77715a1025857d8bd5af

feat: add Lynx frame docs

---

docs/en/guide/performance/metrics/rendering-time.mdx
docs/zh/guide/performance/metrics/rendering-time.mdx

Change-Id: I460d78498000f00b9881f03e2148c2e917df48fc

update rendering time fcp metic figure.

---

docs/en/rspeedy/_meta.json
docs/en/rspeedy/runtime-profiling.md
docs/zh/rspeedy/_meta.json
docs/zh/rspeedy/runtime-profiling.md
rspress.config.ts

Change-Id: I0d73c9a8c57ffecf809fae89538a261c209033de

docs(rspeedy): add runtime profiling

---

rspress.config.ts

Change-Id: Id06bbe5d981b4f584f995cae49c9e00df3a25d99

feat: verify docsearch

---

docs/en/api/elements/built-in/view.mdx
docs/zh/api/elements/built-in/view.mdx

Change-Id: Ide877e1e030e03014c8a74c8ffeabc64aede7232

fix: use english in the picture.

---

docs/en/api/lynx-api/lynx/lynx-request-animation-frame.mdx
docs/zh/api/lynx-api/lynx/lynx-request-animation-frame.mdx
packages/lynx-example-packages/package.json
pnpm-lock.yaml

Change-Id: I56104fff27f51970fedca0e2457cc947f7d60b94

chore: Add requestAnimationFrame demo

---

.cspell/dictionary.txt
docs/en/api/_meta.json
docs/en/api/elements/xelement/_meta.json
docs/en/api/elements/xelement/input.mdx
docs/en/api/elements/xelement/textarea.mdx
docs/en/guide/start/fragments/android/integrating-lynx-with-existing-app-android.mdx
docs/en/guide/start/fragments/ios/integrating-lynx-with-existing-app-ios.mdx
docs/zh/api/elements/xelement/_meta.json
docs/zh/api/elements/xelement/input.mdx
docs/zh/api/elements/xelement/textarea.mdx
docs/zh/guide/start/fragments/android/integrating-lynx-with-existing-app-android.mdx
docs/zh/guide/start/fragments/ios/integrating-lynx-with-existing-app-ios.mdx
i18n.json
packages/lynx-compat-data/elements/input.json
packages/lynx-compat-data/elements/textarea.json
packages/lynx-example-packages/package.json
pnpm-lock.yaml

Change-Id: I9d16f73aca65fb5607699b1cfce52bd8a9de825b

feat: Add docs for input and textarea

---

docs/zh/api/_meta.json
packages/lynx-compat-data/elements/input.json
packages/lynx-compat-data/elements/textarea.json

fix(compat-data): disable input and textarea elements for web_lynx
Change-Id: I6979e5815dbaac6ebf76e9af7cf660ba6b1acb33

docs(api): add xelement to zh sidebar navigation

---

docs/en/api/lynx-api/main-thread/_meta.json
docs/en/api/lynx-api/main-thread/lynx-animate-api.mdx
docs/en/api/lynx-api/main-thread/main-thread-element.mdx
docs/zh/api/lynx-api/main-thread/_meta.json
docs/zh/api/lynx-api/main-thread/lynx-animate-api.mdx
docs/zh/api/lynx-api/main-thread/main-thread-element.mdx
packages/lynx-compat-data/lynx-api/main-thread/Element.json
packages/lynx-compat-data/lynx-api/main-thread/ElementAnimate.json
packages/lynx-compat-data/lynx-api/main-thread/MainThread-APIs.json

Add Docs for MTS `animate` API

feat: add docs for animate API in MTS

---

docs/en/rspeedy/upgrade.mdx

Change-Id: I230d3626b75e30167fb2e68a6dca635320d2c73f

fix: rspeedy version typo

---

docs/en/guide/start/fragments/harmony/integrating-lynx-with-existing-app-harmony.mdx
docs/zh/guide/start/fragments/harmony/integrating-lynx-with-existing-app-harmony.mdx

Change-Id: Id5f8d00b40c28397d0cf4a3543bb357bc79df22d

opt: optimize the doc of integrating for Harmony

---

theme/index.scss
theme/index.tsx

Also, allow overriding the HomeLayout by props.

feat: add `create` command to homepage

---

docs/en/api/lynx-native-api/trace-event.mdx
docs/en/guide/performance/analysis/custom-trace.mdx
docs/zh/api/lynx-native-api/trace-event.mdx
docs/zh/guide/performance/analysis/custom-trace.mdx
packages/lynx-compat-data/lynx-native-api/trace-event.json

Change-Id: I1bdb24f09127c3baad003fbe935d93205129b26c

docs: add harmony trace event api docs

---

packages/lynx-compat-data/elements/common.json
packages/lynx-compat-data/elements/frame.json
packages/lynx-compat-data/elements/image.json
packages/lynx-compat-data/elements/inline-truncation.json
packages/lynx-compat-data/elements/input.json
packages/lynx-compat-data/elements/list-item.json
packages/lynx-compat-data/elements/list.json
packages/lynx-compat-data/elements/nested-image.json
packages/lynx-compat-data/elements/nested-text.json
packages/lynx-compat-data/elements/scroll-view.json
packages/lynx-compat-data/elements/text.json
packages/lynx-compat-data/elements/textarea.json
packages/lynx-compat-data/elements/view.json
packages/lynx-compat-data/index.ts
packages/lynx-compat-data/platforms/clay_ios.json
packages/lynx-compat-data/platforms/platform-keys.json
packages/lynx-compat-data/platforms/platforms.json
packages/lynx-compat-data/types/types.d.ts
src/components/api-badge/PlatformBadge.tsx
src/components/api-table/compat-table/headers.tsx

As title described
Change-Id: I1d99d7102598c911b8097debf55da358ef1c61cb

feat: add compat support informations

---

docs/en/guide/ui/layout/index.mdx
docs/zh/guide/ui/layout/index.mdx

Change-Id: I24118c9009b12370de93079762b9863d2af4effe

opt: optimize the details about logical properties in internationalize

---

src/components/platform-tabs/PlatformTabs.tsx

Change-Id: Ie937b80182ad47db225835d07bf0b13eab778555

docs: add Windows in `PlatformTabs`

---

docs/en/rspeedy/styling.mdx

Change-Id: Idee6ed12dc208927f5db768742abbe198a338ffb

fix: tailwindcss docs code format

---

docs/en/api/lynx-api/performance-api/performance-entry/reload-bundle-entry.mdx
docs/zh/api/lynx-api/performance-api/performance-entry/reload-bundle-entry.mdx

optimize reloadBundleEntry documentation in both English and Chinese
Change-Id: I5c933375af4d6f6560dec0634c490267f8e277a3

feat(performance-api): optimize reloadBundleEntry documentation (#381)

---

docs/en/guide/devtool/recorder.mdx
docs/zh/guide/devtool/recorder.mdx

Change-Id: I15a7bfa9d5411f0a935bc8b415eb91cdee0ea413

doc: Optimize the structure of the recorder guide document

---

packages/lynx-compat-data/css/properties/clip-path.json

clay support clip-path

---

docs/zh/guide/performance.mdx

Change-Id: I1c5edcdcbb8e6fce73f83dd6b2216c4fe3ecf5e0

doc: Remove performance overview
