docs/en/react/lifecycle.mdx, docs/zh/react/lifecycle.mdx
The image url was pasted twice, resulting in a broken image on the page:
https://lynxjs.org/react/lifecycle.html
Correct url is just https://lf-lynx.tiktok-cdns.com/obj/lynx-artifacts-oss-sg/lynx-website/assets/lifecycle-init-render-1.png
=> fix: Broken Lifecycle Image URL in Markdown

docs/en/guide/start/tutorial-gallery.mdx, docs/zh/guide/start/tutorial-gallery.mdx
Current tutorial-gallery only displayed a single file which may confuse readers.It make the tutorial hard to follow step by step. So in this PR we add more entries and highlights in Go components to make the changes and steps more clear and easy to understand.
=> feat: Add more entries and highlights in tutorial-gallery

docs/en/api/elements/built-in/view.mdx, docs/en/api/lynx-api/performance-api/framework-pipeline-timing.mdx, docs/en/api/lynx-api/performance-api/performance-entry/metric-actual-fmp-entry.mdx, docs/en/api/lynx-api/performance-api/performance-entry/metric-fcp-entry.mdx, docs/en/api/lynx-api/performance-api/performance-entry/metric-tti-entry.mdx, docs/en/api/lynx-api/performance-api/performance-entry/pipeline-entry.mdx, docs/en/guide/performance/timing-flag.mdx, docs/zh/api/elements/built-in/view.mdx, docs/zh/api/lynx-api/performance-api/framework-pipeline-timing.mdx, docs/zh/api/lynx-api/performance-api/performance-entry/metric-actual-fmp-entry.mdx, docs/zh/api/lynx-api/performance-api/performance-entry/metric-fcp-entry.mdx, docs/zh/api/lynx-api/performance-api/performance-entry/metric-tti-entry.mdx, docs/zh/api/lynx-api/performance-api/performance-entry/pipeline-entry.mdx
- Standardize "loading TemplateBundle" terminology across docs
- Update DSL default value from reactlynx3 to reactlynx
- Refine metric generation conditions for ActualFmp/FCP/TTI
- Clarify `__lynx_timing_flag` monitoring scope
=> docs(performance): unify metric terminology and documentation standards

theme/index.scss
Change-Id: I8eedc80abaf362d1b107acfa11ab6da6a47db36e
- The issue was observed on the iPad mini and Redmi 12 5G. These were the only devices available for testing, so it may be occurring on other small mobile or tablet devices as well.
- PFA: Screenshots of iPad mini  
| Before             | After              |
|--------------------|--------------------|
| ![Before](https://github.com/user-attachments/assets/f70d33c4-5410-450d-956f-7c47d934cdde) | ![After](https://github.com/user-attachments/assets/729901d1-4411-4fd2-b5b1-03ebefdad17b) |
=> [BugFix] [ui] Hero Text is overflowing out of screen for some phone and tablet devices

rspress.config.ts
Currently when you press the "View source" button it leads to the wrong page as it seems to go to an old reference. See:
Previously it would go to: https://github.com/lynx-wg/lynx-website/tree/main/packages/lynx-compat-data/css/properties/image-rendering.json (does not exist)
Should go now to: https://github.com/lynx-family/lynx-website/blob/main/packages/lynx-compat-data/css/properties/image-rendering.json
Change-Id: Ib300ca30c7b287acd5f466ad811e934c7a48b127
=> fix(config): lynx-wg -> lynx-family in DOC_GIT_BASE_URL

docs/en/guide/start/fragments/web/integrating-lynx-with-web.mdx
Initially I tried to run the bundle as is presented in the docs `main.lynx.bundle`, it's much clearer to use `main.web.bundle` so there are no confusion to which bundle to use.
close: #55
=> Use the default bundle name for web

docs/en/guide/start/fragments/web/integrating-lynx-with-web.mdx, docs/zh/guide/start/fragments/web/integrating-lynx-with-web.mdx
According to the above steps, the URL here should be written as url="/main.web.bundle" instead of url="/main.lynx.bundle". If url="/main.lynx.bundle" is used, the page will not display correctly.
=> fix wrong code in integrating-lynx-with-web

docs/en/guide/ui/scrolling.mdx
fix list example preview img url
fix: #60
=> fix: guide-ui list preview img url

docs/en/api/lynx-api/performance-api/performance-entry/metric-actual-fmp-entry.mdx, docs/en/api/lynx-api/performance-api/performance-entry/metric-fcp-entry.mdx, docs/zh/api/lynx-api/performance-api/performance-entry/metric-actual-fmp-entry.mdx, docs/zh/api/lynx-api/performance-api/performance-entry/metric-fcp-entry.mdx
In this CR, we have clarified the timing and content of sending metric performance entry. Due to the instability in recording container-related timestamps, we cannot guarantee that all metrics will be provided each time. Therefore, we may send metric performance entry multiple times.
Change-Id: I3076a476aaf683d9fec99767b787208ca223cefd
=> [Optimize] Clarify the timing and content of sending metric entry

docs/en/blog/_meta.json, docs/zh/blog/_meta.json
Change-Id: Ifd0160e421e0081d701f06f0fdc7418178eeead3
PrevNextPage is generated based on Sidebar, so it should be included in "_meta.json"
before
after
=> fix(blog): PrevNextPage should point to the blog

docs/en/api/lynx-api/performance-api/performance-entry.mdx, docs/en/api/lynx-native-api/lynx-view/set-extra-timing.mdx, docs/zh/api/lynx-api/performance-api/performance-entry.mdx, docs/zh/api/lynx-native-api/lynx-view/set-extra-timing.mdx
Added definition of special behavior for repeated calls to setExtraTiming.
Added description of possible consequences of calling setExtraTiming.
Standardized references to the term `Container` in all documents.
Change-Id: Icfaf2a844b1b3f921491cb8e1fb1d932da57c5d8
=> opt: Optimize setExtraTiming API Doc. Correct the format of 'Container'.

docs/en/react/code-splitting.md
There was a typo in the conditional rendering of the lazyload component. We don't have a component called `shouldShow`. It's supposed to be `shouldDisplay`
=> State Variable Fix (shouldShow to shouldDisplay)

docs/zh/react/code-splitting.md
lazyload 组件的条件渲染中有一个拼写错误。我们没有名为 shouldShow 的组件。应该是 shouldDisplay
=> 状态变量修复（shouldShow 改为 shouldDisplay)

docs/en/api/lynx-testing-environment/index.mdx, docs/zh/api/lynx-testing-environment/index.mdx
Fix `https://lynxjs.org/react/react-lynx-testing-library.html` -> `https://lynxjs.org/react/reactlynx-testing-library.html`
=> fix: correct link to testing library docs

docs/en/guide/custom-native-modules/_meta.json, docs/zh/guide/custom-native-modules/_meta.json, rspress.config.ts
The document fragment should all be added to `route.exclude`
custom-native-modules uses `_meta.json`, so I misunderstood.
related https://github.com/lynx-family/lynx-website/pull/152
1. add imports for themselves
2. add to `route.exclude`
=> fix(rspress): mdx fragments should be added to route.exclude

docs/en/react/reactlynx-testing-library.mdx, docs/zh/react/reactlynx-testing-library.mdx
Aligning testing docs with https://github.com/lynx-family/lynx-stack/blob/main/packages/react/testing-library/README.md
=> Add missing wrapper to `Basic rendering` example in reactlynx-testing-library.mdx

docs/en/rspeedy/typescript.md, docs/zh/rspeedy/typescript.md
This patch adds instructions on how to extend Lynx types, including `GlobalProps` and `InitData`.
see: https://github.com/lynx-family/lynx-website/issues/183
=> docs: add "extending Lynx types"

docs/en/api/elements/built-in/scroll-view.mdx, docs/zh/api/elements/built-in/scroll-view.mdx, packages/lynx-compat-data/elements/scroll-view.json
update scroll-view docs
1. Update the parameter types of `initial-scroll-offset` and `initial-scroll-to-index` from String to Number.
2. Update compatibility data,`initial-scroll-offset` and `scroll-orientation` are currently not supported on the HarmonyOS.
=> docs: update scroll-view docs

docs/en/api/css/data-type/color.mdx, packages/lynx-compat-data/css/data-type/color.json
hsla dosen't support modern syntax
=> fix: inconsistent between zh and en for hsla syntax

docs/en/guide/inclusion/internationalization.mdx, docs/en/guide/start/integrate-lynx-dev-version.mdx, docs/en/rspeedy/typescript.md, docs/zh/guide/inclusion/internationalization.mdx, docs/zh/guide/start/integrate-lynx-dev-version.mdx, docs/zh/rspeedy/typescript.md, rspress.config.ts
Use `[!code ++]`, `[!code --]`, `[!code highlight]` and `[!code focus]` to make better looking documentation.
See: 
- diff: https://shiki.style/packages/transformers#transformernotationdiff
- highlight: https://shiki.style/packages/transformers#transformernotationhighlight
- focus: https://shiki.style/packages/transformers#transformernotationfocus
=> docs: use shiki diff and focus

rspress.config.ts, src/components/api-table/compat-table/index.tsx
This pull request updates the configuration and logic for displaying platform support in the compatibility table. The main change is the introduction of a new environment variable to control whether the "clay" platform is shown, improving flexibility for different deployments.
**Configuration and feature flag changes:**
* Added a new environment variable `COMPAT_TABLE_HIDE_CLAY` to the `process.env` config in `rspress.config.ts` to control the visibility of the "clay" platform in compatibility tables.
**Compatibility table logic updates:**
* Updated the logic in `gatherPlatformsAndBrowsers` in `src/components/api-table/compat-table/index.tsx` to use the new `COMPAT_TABLE_HIDE_CLAY` environment variable instead of `OSS` for determining which platforms to display.Change-Id: …
=> chore: change flag name

docs/zh/index.mdx
This pull request updates internal documentation links in the Chinese homepage to ensure they point to the correct localized blog and guide pages.
Documentation link corrections:
* Updated the "介绍" link in the `hero` section of `docs/zh/index.mdx` to use the Chinese blog URL.
* Updated the "快速开始" link in the `hero` section of `docs/zh/index.mdx` to use the Chinese quick start guide URL.
Change-Id: I9de674262973ff278accbbfed8272b4aef921fd3
=> fix: home page zh link

docs/en/api/lynx-api/event/event.mdx, docs/zh/api/lynx-api/event/event.mdx, packages/lynx-compat-data/lynx-api/event/Event.json
Remove `event.stopPropgation` and `event.stopImmediatPropgation`, cause these method doesn't exist prior Lynx 3.5
=> feat: remove stopPropgation in event
